// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFmiBF--3nMtekp6GyCHUToea6T6pyq34',
    appId: '1:229705098209:web:4e80ab5a8a202513a768a0',
    messagingSenderId: '229705098209',
    projectId: 'ibreezfb',
    authDomain: 'ibreezfb.firebaseapp.com',
    storageBucket: 'ibreezfb.appspot.com',
    measurementId: 'G-MSVZ6EHJD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAb8rZ2IWUtmAlqavRie7PysqFxuvMnEs',
    appId: '1:229705098209:android:8f7ae23004187ef7a768a0',
    messagingSenderId: '229705098209',
    projectId: 'ibreezfb',
    storageBucket: 'ibreezfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj6Mopn9oXQR0JcPWhF-8AmNdHwgCWOEc',
    appId: '1:229705098209:ios:f4fb01d4dc9b82c4a768a0',
    messagingSenderId: '229705098209',
    projectId: 'ibreezfb',
    storageBucket: 'ibreezfb.appspot.com',
    iosBundleId: 'com.example.ibreezfb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFmiBF--3nMtekp6GyCHUToea6T6pyq34',
    appId: '1:229705098209:web:51249cba388c6350a768a0',
    messagingSenderId: '229705098209',
    projectId: 'ibreezfb',
    authDomain: 'ibreezfb.firebaseapp.com',
    storageBucket: 'ibreezfb.appspot.com',
    measurementId: 'G-891VCDFLEG',
  );
}
